"""Initial schema

Revision ID: 424f6ea2477e
Revises: 
Create Date: 2026-03-09 15:07:13.430071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424f6ea2477e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='params_store'
    )
    op.create_index(op.f('ix_params_store_users_id'), 'users', ['id'], unique=False, schema='params_store')
    op.create_index(op.f('ix_params_store_users_username'), 'users', ['username'], unique=True, schema='params_store')
    op.create_table('parameters',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('encrypted_dek', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['params_store.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'app', 'name'),
    schema='params_store'
    )
    op.create_index(op.f('ix_params_store_parameters_app'), 'parameters', ['app'], unique=False, schema='params_store')
    op.create_index(op.f('ix_params_store_parameters_name'), 'parameters', ['name'], unique=False, schema='params_store')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_params_store_parameters_name'), table_name='parameters', schema='params_store')
    op.drop_index(op.f('ix_params_store_parameters_app'), table_name='parameters', schema='params_store')
    op.drop_table('parameters', schema='params_store')
    op.drop_index(op.f('ix_params_store_users_username'), table_name='users', schema='params_store')
    op.drop_index(op.f('ix_params_store_users_id'), table_name='users', schema='params_store')
    op.drop_table('users', schema='params_store')
    # ### end Alembic commands ###
